In [3]:
import pandas as pd
data=pd.read_csv("novagen_dataset.csv")

In [4]:
data

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9544,5.0,22.0,109.0,203.0,98.0,75.0,8.0,1.0,6.0,0.0,...,0,2,2,1,0,True,False,True,False,False
9545,94.0,26.0,144.0,203.0,96.0,72.0,8.0,4.0,2.0,1.0,...,1,0,1,0,2,False,True,False,True,False
9546,10.0,23.0,185.0,198.0,103.0,72.0,4.0,5.0,5.0,6.0,...,1,0,2,0,1,True,False,True,False,False
9547,50.0,29.0,166.0,200.0,100.0,74.0,8.0,2.0,3.0,4.0,...,2,0,0,1,1,True,False,True,False,False
9548,69.0,29.0,178.0,203.0,100.0,75.0,10.0,-0.0,6.0,2.0,...,1,2,1,2,0,False,False,True,False,False

In [8]:
x=data.drop("Target",axis=1)

In [10]:
y=data["Target"]

In [11]:
x

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9544,5.0,22.0,109.0,203.0,98.0,75.0,8.0,1.0,6.0,0.0,...,0,2,2,1,0,True,False,True,False,False
9545,94.0,26.0,144.0,203.0,96.0,72.0,8.0,4.0,2.0,1.0,...,1,0,1,0,2,False,True,False,True,False
9546,10.0,23.0,185.0,198.0,103.0,72.0,4.0,5.0,5.0,6.0,...,1,0,2,0,1,True,False,True,False,False
9547,50.0,29.0,166.0,200.0,100.0,74.0,8.0,2.0,3.0,4.0,...,2,0,0,1,1,True,False,True,False,False
9548,69.0,29.0,178.0,203.0,100.0,75.0,10.0,-0.0,6.0,2.0,...,1,2,1,2,0,False,False,True,False,False

In [12]:
y

0       1
1       1
2       0
3       0
4       0
       ..
9544    0
9545    0
9546    0
9547    0
9548    0
Name: Target, Length: 9549, dtype: int64

In [13]:
x.isnull().sum()

Age                      0
BMI                      0
Blood_Pressure           0
Cholesterol              0
Glucose_Level            0
Heart_Rate               0
Sleep_Hours              0
Exercise_Hours           0
Water_Intake             0
Stress_Level             0
Smoking                  0
Alcohol                  0
Diet                     0
MentalHealth             0
PhysicalActivity         0
MedicalHistory           0
Allergies                0
Diet_Type__Vegan         0
Diet_Type__Vegetarian    0
Blood_Group_AB           0
Blood_Group_B            0
Blood_Group_O            0
dtype: int64

In [14]:
y.isnull().sum()

0

In [43]:
x = x.astype(int)
x

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2,26,111,198,99,72,4,1,5,5,...,1,2,1,0,1,0,1,1,0,0
1,8,24,121,199,103,75,2,1,2,9,...,1,2,1,2,2,0,0,1,0,0
2,81,27,147,203,100,74,10,0,5,1,...,2,0,0,1,0,1,0,0,0,0
3,25,21,150,199,102,70,7,3,3,3,...,1,2,1,2,0,1,0,0,1,0
4,24,26,146,202,99,76,10,2,5,1,...,2,0,2,0,2,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9544,5,22,109,203,98,75,8,1,6,0,...,0,2,2,1,0,1,0,1,0,0
9545,94,26,144,203,96,72,8,4,2,1,...,1,0,1,0,2,0,1,0,1,0
9546,10,23,185,198,103,72,4,5,5,6,...,1,0,2,0,1,1,0,1,0,0
9547,50,29,166,200,100,74,8,2,3,4,...,2,0,0,1,1,1,0,1,0,0
9548,69,29,178,203,100,75,10,0,6,2,...,1,2,1,2,0,0,0,1,0,0

In [28]:
x

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2,26,111,198,99,72,4,1,5,5,...,1,2,1,0,1,0,1,1,0,0
1,8,24,121,199,103,75,2,1,2,9,...,1,2,1,2,2,0,0,1,0,0
2,81,27,147,203,100,74,10,0,5,1,...,2,0,0,1,0,1,0,0,0,0
3,25,21,150,199,102,70,7,3,3,3,...,1,2,1,2,0,1,0,0,1,0
4,24,26,146,202,99,76,10,2,5,1,...,2,0,2,0,2,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9544,5,22,109,203,98,75,8,1,6,0,...,0,2,2,1,0,1,0,1,0,0
9545,94,26,144,203,96,72,8,4,2,1,...,1,0,1,0,2,0,1,0,1,0
9546,10,23,185,198,103,72,4,5,5,6,...,1,0,2,0,1,1,0,1,0,0
9547,50,29,166,200,100,74,8,2,3,4,...,2,0,0,1,1,1,0,1,0,0
9548,69,29,178,203,100,75,10,0,6,2,...,1,2,1,2,0,0,0,1,0,0

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
model=LogisticRegression()

In [31]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

## SCALING THE DATA ##

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [51]:
model.fit(x_train_scaled,y_train)
y_pred=model.predict(x_test_scaled)

In [53]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.8184991273996509
[[1090  266]
 [ 254 1255]]
              precision    recall  f1-score   support

           0       0.81      0.80      0.81      1356
           1       0.83      0.83      0.83      1509

    accuracy                           0.82      2865
   macro avg       0.82      0.82      0.82      2865
weighted avg       0.82      0.82      0.82      2865